# ============================================================
# Create the release signing key, once. (PowerShell)
#   .\scripts\make-keystore.ps1
# ============================================================
#
# The PowerShell twin of make-keystore.sh. Both exist because `bash` on a
# default Windows PATH is WSL's bash, not Git Bash — it cannot run a script
# against Windows paths, and fails in a way that looks like nothing happened.
#
# Creates trikekoto-release.jks and writes android\key.properties to match, so
# there is no second step where the alias or the path can be typed wrong.
#
# The password is read from your terminal and passed to keytool through the
# environment, never as an argument. Arguments are visible in shell history and
# in the process list; this is a key you can never rotate, so that matters.

$ErrorActionPreference = 'Stop'

Set-Location (Join-Path $PSScriptRoot '..')
$Keystore = 'trikekoto-release.jks'
$Props    = 'android\key.properties'
$Alias    = 'trikekoto'

# ── Refuse to clobber ────────────────────────────────────────
# Overwriting a keystore that has already signed an installed APK means no
# device holding that APK can ever be updated. Never make that easy.
if (Test-Path $Keystore) {
  Write-Host "ERROR: $Keystore already exists." -ForegroundColor Red
  Write-Host ""
  Write-Host "If it signed an APK anyone has installed, replacing it means every one"
  Write-Host "of them must uninstall and reinstall. Move it aside deliberately if you"
  Write-Host "are certain it was never used."
  exit 1
}

if (-not (Get-Command keytool -ErrorAction SilentlyContinue)) {
  Write-Host "ERROR: keytool not found. It ships with the JDK - check JAVA_HOME." -ForegroundColor Red
  exit 1
}

Write-Host @'
-- TrikeKoTo release signing key ---------------------------

This key is your app's permanent identity. Android ties an installed app to
the key that signed it, so:

  * Lose it and you can never update an installed app. Not "difficult" --
    impossible. Every driver would have to uninstall and reinstall.
  * Replace it and the same thing happens.

Back up both the .jks file and the password somewhere that is not this
laptop and not this repository, before you ship anything.

'@

# ── Password, read from the terminal ─────────────────────────
function Read-Plain($prompt) {
  $secure = Read-Host -Prompt $prompt -AsSecureString
  $bstr = [System.Runtime.InteropServices.Marshal]::SecureStringToBSTR($secure)
  try {
    return [System.Runtime.InteropServices.Marshal]::PtrToStringAuto($bstr)
  } finally {
    [System.Runtime.InteropServices.Marshal]::ZeroFreeBSTR($bstr)
  }
}

$pw = Read-Plain 'Choose a password (at least 6 characters)'
if ($pw.Length -lt 6) {
  Write-Host "ERROR: keytool requires at least 6 characters." -ForegroundColor Red
  exit 1
}
$pw2 = Read-Plain 'Type it again'
if ($pw -ne $pw2) {
  Write-Host "ERROR: they do not match. Nothing was created." -ForegroundColor Red
  exit 1
}

# keytool reads this from the environment rather than from argv.
$env:TK_STOREPASS = $pw

Write-Host ""
Write-Host "keytool will now ask for your name and organisation. Any sensible"
Write-Host "answer is fine - none of it is checked, and it is only shown in the"
Write-Host "certificate."
Write-Host ""
Write-Host "At the last question - 'Is CN=... correct?' - the default is no." -ForegroundColor Yellow
Write-Host "You must type yes, or it loops back and asks everything again." -ForegroundColor Yellow
Write-Host ""

keytool -genkeypair -v `
  -keystore $Keystore `
  -alias $Alias `
  -keyalg RSA -keysize 2048 -validity 10000 `
  "-storepass:env" TK_STOREPASS `
  "-keypass:env" TK_STOREPASS

if (-not (Test-Path $Keystore)) {
  Write-Host "ERROR: keytool did not create $Keystore. Nothing else was written." -ForegroundColor Red
  $env:TK_STOREPASS = $null
  exit 1
}

# ── key.properties, generated rather than typed ──────────────
$content = @"
# Generated by scripts/make-keystore.ps1 - gitignored, holds your key password.
storePassword=$pw
keyPassword=$pw
keyAlias=$Alias
storeFile=../$Keystore
"@
Set-Content -Path $Props -Value $content -Encoding ascii

# ── Confirm it is usable ─────────────────────────────────────
# Read back through keytool rather than trusting that the write succeeded.
Write-Host ""
Write-Host "-- Certificate ---------------------------------------------"
keytool -list -v -keystore $Keystore "-storepass:env" TK_STOREPASS 2>$null |
  Select-String -Pattern 'Alias name|Owner:|Valid from'

$env:TK_STOREPASS = $null
$pw = $null; $pw2 = $null

Write-Host ""
Write-Host "-- Done ----------------------------------------------------"
Write-Host ""
Write-Host "  Keystore     $(Join-Path (Get-Location) $Keystore)"
Write-Host "  Properties   $(Join-Path (Get-Location) $Props)"
Write-Host ""
Write-Host "Both are gitignored. Build a signed APK with:"
Write-Host ""
Write-Host "  flutter build apk --release"
Write-Host ""
Write-Host "Then confirm the certificate is yours, not Android's debug key:"
Write-Host ""
Write-Host "  apksigner verify --print-certs build/app/outputs/flutter-apk/app-release.apk"
Write-Host ""
Write-Host "Back up the .jks and the password now, offline, before you ship." -ForegroundColor Yellow
