#!/usr/bin/env bash
# ============================================================
# Create the release signing key, once.
#   bash scripts/make-keystore.sh
# ============================================================
#
# Creates trikekoto-release.jks and writes android/key.properties to match, so
# there is no second step where the alias or the path can be typed wrong — a
# mismatch there produces a Gradle error that names neither.
#
# The password is read from your terminal and passed to keytool through the
# environment, never as an argument. Arguments are visible in shell history and
# in the process list; this is a key you can never rotate, so that matters.
#
# Run it yourself. Nobody else should ever know this password.

set -euo pipefail

cd "$(dirname "$0")/.."
KEYSTORE="trikekoto-release.jks"
PROPS="android/key.properties"
ALIAS="trikekoto"

# ── Refuse to clobber ────────────────────────────────────────
# Overwriting a keystore that has already signed an installed APK means no
# device holding that APK can ever be updated. Never make that easy.
if [[ -f "$KEYSTORE" ]]; then
  echo "ERROR: $KEYSTORE already exists."
  echo
  echo "If it signed an APK anyone has installed, replacing it means every one"
  echo "of them must uninstall and reinstall. Move it aside deliberately if you"
  echo "are certain it was never used."
  exit 1
fi

if ! command -v keytool >/dev/null 2>&1; then
  echo "ERROR: keytool not found. It ships with the JDK — check JAVA_HOME."
  exit 1
fi

cat <<'INTRO'
── TrikeKoTo release signing key ───────────────────────────

This key is your app's permanent identity. Android ties an installed app to
the key that signed it, so:

  * Lose it and you can never update an installed app. Not "difficult" —
    impossible. Every driver would have to uninstall and reinstall.
  * Replace it and the same thing happens.

Back up both the .jks file and the password somewhere that is not this
laptop and not this repository, before you ship anything.

INTRO

# ── Password, read from the terminal ─────────────────────────
read -r -s -p "Choose a password (at least 6 characters): " PW; echo
if [[ ${#PW} -lt 6 ]]; then
  echo "ERROR: keytool requires at least 6 characters."
  exit 1
fi
read -r -s -p "Type it again: " PW2; echo
if [[ "$PW" != "$PW2" ]]; then
  echo "ERROR: they do not match. Nothing was created."
  exit 1
fi
echo

# keytool reads this from the environment rather than from argv.
export TK_STOREPASS="$PW"

echo "keytool will now ask for your name and organisation. Any sensible"
echo "answer is fine — none of it is checked, and it is only shown in the"
echo "certificate."
echo

keytool -genkeypair -v \
  -keystore "$KEYSTORE" \
  -alias "$ALIAS" \
  -keyalg RSA -keysize 2048 -validity 10000 \
  -storepass:env TK_STOREPASS \
  -keypass:env TK_STOREPASS

# ── key.properties, generated rather than typed ──────────────
umask 077
cat > "$PROPS" <<EOF
# Generated by scripts/make-keystore.sh — gitignored, holds your key password.
storePassword=$PW
keyPassword=$PW
keyAlias=$ALIAS
storeFile=../$KEYSTORE
EOF

# ── Confirm it is usable ─────────────────────────────────────
# Read back through keytool rather than trusting that the write succeeded.
echo
echo "── Certificate ─────────────────────────────────────────────"
keytool -list -v -keystore "$KEYSTORE" -storepass:env TK_STOREPASS \
  2>/dev/null | grep -E "Alias name|Owner:|Valid from" || {
    echo "WARNING: could not read the keystore back. Check it by hand."
  }

unset TK_STOREPASS PW PW2

cat <<EOF

── Done ────────────────────────────────────────────────────

  Keystore       $PWD/$KEYSTORE
  Properties     $PWD/$PROPS

Both are gitignored. Build a signed APK with:

  flutter build apk --release

Then confirm the certificate is yours, not Android's debug key:

  apksigner verify --print-certs build/app/outputs/flutter-apk/app-release.apk

Back up the .jks and the password now, offline, before you ship.
EOF
