// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4dy7KIUMVC53bbCoCEBAytQDsUtiXASU',
    appId: '1:877860610923:web:010d2ae54474bc2455222e',
    messagingSenderId: '877860610923',
    projectId: 'trikekoto',
    authDomain: 'trikekoto.firebaseapp.com',
    databaseURL: 'https://trikekoto-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'trikekoto.firebasestorage.app',
    measurementId: 'G-F38GCG1RCK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAXyTOY-ou43KMJESLX2Uu7HHvZokruvE',
    appId: '1:877860610923:android:77bd8e86770a873855222e',
    messagingSenderId: '877860610923',
    projectId: 'trikekoto',
    databaseURL: 'https://trikekoto-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'trikekoto.firebasestorage.app',
  );
}
